In [1]:
##Zip()

In [2]:
languages=['Java','Python','JavaScript']
versions=[14,3,6]

In [3]:
result=zip(languages,versions)
print(list(result))

[('Java', 14), ('Python', 3), ('JavaScript', 6)]


In [4]:
##Pandas

In [5]:
data={'Name':['Tom','nick','krish','jack'],'Age':[20,21,19,18]}

In [6]:
import pandas as pd
dfemp=pd.DataFrame(data)
print(dfemp)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [7]:
dfser=pd.Series(dfemp['Age'])
dfser.head(3)

0    20
1    21
2    19
Name: Age, dtype: int64

In [8]:
result1=dfser.apply(lambda x:21 if x ==19 else x)

In [9]:
print(result1)

0    20
1    21
2    21
3    18
Name: Age, dtype: int64


In [10]:
##Numpy Arrays

In [11]:
#Array Creation Functions
#np.array(),np.zeros(),np.ones(),np.empty()

In [12]:
import numpy as np
array1=np.array([1,3,5])
print("np.array():\n",array1)

np.array():
 [1 3 5]


In [13]:
array2=np.zeros((3,3))
print("\nnp.zeros():\n",array2)


np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
array3=np.ones((2,4))
print("\nnp.ones():\n",array3)


np.ones():
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
array4=np.random.randint(low=1,high=10,size=(3,4))

In [16]:
print(array4)

[[1 5 3 3]
 [1 4 9 4]
 [3 4 2 8]]


In [17]:
array5=np.random.randint(100,size=(3,4))
print(array5)

[[19 88 98 61]
 [69 73  8  7]
 [ 6 20 92 55]]


In [18]:
##Array Manipulation Functions
#np.reshape(),np.transpose()

In [19]:
array6=np.array([1,3,5,7,9,11])
array7=np.reshape(array6,(2,3))
print(array7)

[[ 1  3  5]
 [ 7  9 11]]


In [20]:
array8=np.transpose(array7)
print(array8)

[[ 1  7]
 [ 3  9]
 [ 5 11]]


In [21]:
#Array Input and Output Functions
#np.save(),np.loadtxt()

In [22]:
arr=np.array([[1,3,5],[2,4,6]])

In [23]:
np.savetxt('data.txt',arr)

In [24]:
loaded_data=np.loadtxt('data.txt')

In [25]:
print(loaded_data)

[[1. 3. 5.]
 [2. 4. 6.]]


In [26]:
#Scipy
#2x+y=5
#4x-5y=7

In [27]:
a=np.array([[2,1],[4,-5]])
b=np.array([[5],[7]])

In [28]:
from scipy import linalg
x=linalg.solve(a,b)
print(x)

[[2.28571429]
 [0.42857143]]


In [29]:
print(a.dot(x)-b)

[[0.]
 [0.]]


In [30]:
#2x+y=5
#x-3y=-2

In [31]:
a=np.array([[2,1],[1,-3]])
b=np.array([[5],[-2]])

In [32]:
from scipy import linalg
x=linalg.solve(a,b)
print(x)

[[1.85714286]
 [1.28571429]]


In [33]:
res=a.dot(x)-b

In [34]:
#f=lambda res:(abs(res)+res)/2
#f(x)

In [35]:
#res=a.dot(f(x))-b
#print(res.astype(int))

In [36]:
import pandas as pd
result3=pd.DataFrame(res)
print(result3)

              0
0  0.000000e+00
1 -4.440892e-16


In [37]:
result4=result3[0].apply(lambda x:int(x))
print(result4)

0    0
1    0
Name: 0, dtype: int64


In [ ]:
def SalesManagement():
    listprod=[]
    listcust=[]
    saleslist=[]
    while(1):
        a=input("Enter the operation you want to perform?\n 1. Add a new product. \n 2. List all Products \n 3. Add a new Customer \n 4. List all Customers. \n 5. Create a new sales order. \n 6. List all sales order. \n 7. Quit the Program.\n")
        if(a=='1'):
            prod=input("Enter the product name.")
            listprod.append(prod)
        elif(a=='2'):
            print(listprod)
        elif(a=='3'):
            cust=input("Enter the Customer name.")
            listcust.append(cust)
        elif(a=='4'):
            print(listcust)
        elif(a=='5'):
            sales=input("Enter the Order Details")
            saleslist.append(sales)
        elif(a=='6'):
            print(saleslist)
        elif(a=='7'):
            break;

Enter the operation you want to perform?
 1. Add a new product. 
 2. List all Products 
 3. Add a new Customer 
 4. List all Customers. 
 5. Create a new sales order. 
 6. List all sales order. 
 7. Quit the Program.
2
[]
Enter the operation you want to perform?
 1. Add a new product. 
 2. List all Products 
 3. Add a new Customer 
 4. List all Customers. 
 5. Create a new sales order. 
 6. List all sales order. 
 7. Quit the Program.
book
Enter the operation you want to perform?
 1. Add a new product. 
 2. List all Products 
 3. Add a new Customer 
 4. List all Customers. 
 5. Create a new sales order. 
 6. List all sales order. 
 7. Quit the Program.
1
Enter the product name.shivam
Enter the operation you want to perform?
 1. Add a new product. 
 2. List all Products 
 3. Add a new Customer 
 4. List all Customers. 
 5. Create a new sales order. 
 6. List all sales order. 
 7. Quit the Program.
2
['shivam']
